### ISSUE TITLE
Change game path

### ISSUE THREAD

**Issue by Kamakaze22** [BioBox/bsgl#2]
I recently had to reinstall several games onto a new HD. The new HD had a different file path than I originally put into the game loader.  Is it possible to update a file path without having to create a brand new entry?

**Comment by BioBox** [comment]
Inside the directory of the application, there should be an XML file called `index.xml`. You can open it with a text editor of your choice to edit the name and path of all games registered on it.

Let me know if that works for you or not. Sorry for the late reply.
